#!/usr/bin/env bash

CLONE_PATH="$1"

cd "$CLONE_PATH"

if [ "$1" == "" ]
then
    echo "usage: cron-sync <gitsvn-clone-path>"
    echo ""
    exit 0
fi

git pull
git svn dcommit --add-author-from --rmdir --find-copies-harder
exit $?